name: CI
run-name: deployment for Production
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: checkout the current branch
        uses: actions/checkout@v3
       # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
          chmod 777 deploy.tar
      
      - name: SSH into the server and deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Update the port if your SSH server uses a different port
          script: |
            echo ${{ secrets.DEPLOY_PASSWORD }} | sudo -S
          source: "deploy.tar"
          target: "/home/user-data/www/nicee-n-tasty"


