name: CI
run-name: deployment for Production
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: checkout the current branch
        uses: actions/checkout@v3

      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Scan the host key
        run: mkdir -p ~/.ssh/ && ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/know_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      
      - name: Deploy to website
        run: |
          sudo cp -R . /home/user-data/www/nicee-n-tasty
      
      - name: Deploy the Website
        run: >-
          rsync -avx --delete nicee-n-tasty/ $DEPLOY_USERNAME@DEPLOY_SERVER:/home/user-data/www/nicee-n-tasty
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
