name: CI
run-name: deployment for Production
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: checkout the current branch
        uses: actions/checkout@v3
      
      - name: SSH into the server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # Update the port if your SSH server uses a different port
          script: |
            echo ${{ secrets.DEPLOY_PASSWORD }} | sudo rm -rf /home/user-data/www/nicee-n-tasty/*
            sudo cp -R $GITHUB_WORKSPACE/. /home/user-data/www/nicee-n-tasty/
            


